<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.30" />
    <xacro:property name="base_width" value="0.30" />
    <xacro:property name="base_height" value="0.095" />

    <xacro:property name="base_x_offset" value="0.075" />


    <xacro:property name="base_ground" value="0.055" />

    <xacro:property name="wheel_radius" value="0.038" />
    <xacro:property name="wheel_length" value="0.025" />
    <xacro:property name="wheel_support_length" value="${base_ground - wheel_radius}" />

    <xacro:property name="caster_base_x" value="0.16" />
    
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_x_offset} 0 ${base_height/2}" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <collision>
           <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_x_offset} 0 ${base_height/2}" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="0.5" x="${base_length}" y="${base_width}" z="${base_height}" 
            o_xyz="${base_x_offset} 0 ${base_height/2}" o_rpy="0 0 0"/>


    </link>




    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>

            <xacro:cylinder_inertia m="0.01" r="${wheel_radius}" h="${wheel_length}"
                    o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${(wheel_radius + wheel_support_length)}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${ (wheel_radius + wheel_support_length)}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:sphere_inertia m="0.01" r="${ (wheel_radius + wheel_support_length)}"
                o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>





    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${base_ground}" rpy="0 0 0"/>
    </joint>



    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <!-- 0.01 is margin in real world -->
        <origin xyz="0 ${-(base_width + wheel_length + 0.02) / 2.0} -${wheel_support_length }" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <!-- 0.01 is margin in real world -->
        <origin xyz="0 ${(base_width + wheel_length + 0.02) / 2.0} -${wheel_support_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${caster_base_x} 0 0" rpy="0 0 0" />
    </joint>



</robot>